updated old

diff --git a/Block1/stats-old b/Block1/stats-old
--- a/Block1/stats-old
+++ b/Block1/stats-old
@@ -1,131 +1,191 @@
-#!/bin/sh
+#!/bin/bash
 
+function cleanup {	#removes temp files if program is killed
+	if [[ -e $$temprow ]]		#checks if row file exists
+	then
+		rm -f $$temprow
+	fi
+	if [[ -e $$tempMedian ]]		#checks if median file exists
+	then
+		rm -f $$tempMedian
+	fi
+	if [[ -e $$tempAverage ]]		#checks if average file exists
+	then
+		rm -f $$tempAverage
+	fi
+	if [[ -e $$datafile ]]		#checks if datafile exists
+	then
+		rm -f $$datafile
+	fi
+	count=0
+	while [[ -e $$tmpcol* ]]	#removes all column files
+	do
+		rm -f $$tmpcol$count
+		count=`expr $count + 1`
+	done
+	exit 1
+}
 
-echoerr() { echo "$@" 1>&2; }
+trap cleanup SIGHUP SIGINT SIGTERM	#traps kill command
 
-datafilepath="datafile$$"
-if [ "$#" = "1" ]
+echoerr() { echo "$@" 1>&2; }	#to print errors to screen
+
+#check if file or stdin
+datafilepath="$$datafile"
+if [ "$#" = "0" ]	#if nothing is passed in
 then
-    cat > "$datafilepath"
-elif [ "$#" = "2" ]
+	echoerr "./stats {-rows|-cols} [file]"
+	exit 1
+elif [ "$#" = "1" ]		#if it should be read from stdin
 then
-    datafilepath=$2
+	cat > "$datafilepath"
+elif [ "$#" = "2" ]		#if it should be read from provided file
+then
+	datafilepath=$2
+	if [[ ! -e $datafilepath ]]		#checks if file exists
+	then
+		echoerr "./stats cannot read $datafilepath"
+		exit 1
+	elif [[ ! -r $datafilepath ]]	#checks if file has read permission
+	then
+		echoerr "./stats cannot read $datafilepath"
+		exit 1
+	elif [[ ! -f $datafilepath ]]	#checks if file is a regular file (not directory)
+	then
+		echoerr "./stats cannot read $datafilepath"
+		exit 1
+	fi
+else	#if too many options are provided
+	echoerr "./stats {-rows|-cols} [file]"
+	exit 1
 fi
+
+#make temp files
+tmprow="$$temprow"
+tmpAvg="$$tempAverage"
+tmpMed="$$tempMedian"
 
 #Code to calculate for rows
-if [[ $1 == -r* ]];
+if [[ $1 == -r* ]]
 then
-    echo "calculating row stats";
-    echo -e "Average \t Median"
-    while read i #reads all lines
-    do
-	sum=0
-	count=0
-	for num in $i
+	rowRan="false"
+	while read i #reads all lines
 	do
-	  sum=$(($sum + $num)) #adds number to sum total
-	  if [[ $count == 0 ]] #move vales to temp file for sorting
-	  then
-		echo "$num" > $$tempfile #if first line then restart file
-	  else
-	  	echo "$num" >> $$tempfile #otherwise add to file
-	  fi
-	  count=$(($count + 1))
-	done
-	avg=$(($sum / $count)) 
-        rem=$(($sum % $count))
-	while (($rem > ($count / 2))) #checks is average needs rounded up
-        do
-          avg=$(($avg + 1))
-          rem=0
-        done
+		if [[ $rowRan == "false" ]]	#prints headers only on the first run
+		then
+			echo -e "Average\tMedian"
+		fi
+		rowRan="true"
+		sum=0
+		count=0
+		for num in $i
+		do
+			sum=`expr $sum + $num` #adds number to sum total
+			echo "$num" >> $tmprow #saved into temp file for sorting
+			count=`expr $count + 1`
+		done
+		
+		avg=$(( ($sum + ( $count / 2)) / $count ))	#finds average
+		med=`expr $count / 2`	#finds place of median value
+		med=`expr $med + 1`
+		
+		sort -n $tmprow -o $tmprow #sorts temp file
+		
+		tmpcnt=1
+		while read num   #finds median
+		do
+			if [[ $tmpcnt == $med ]]
+			then
+				echo -e "$avg\t$num" #prints results
+			fi
+			tmpcnt=`expr $tmpcnt + 1`
+		done < $tmprow
+		rm -f $tmprow
+	done < $datafilepath
+	if [[ $rowRan == "false" ]]	#checks if it actually ran, if it didn't then the file had nothing to read
+	then
+		echoerr "FILE IS EMPTY"
+		exit 1
+	fi
 
-	med=$(($count / 2 + 1))
-	
-	sort -n $$tempfile -o $$tempsorted #sorts temp file
-
-	tmpcnt=0
-	while read tempnum   #finds median
-	do
-	 tmpcnt=$((tmpcnt + 1))
-	 if [[ $med == $tmpcnt ]]
-	 then
-		med=$tempnum
-	 fi
-	done < $$tempsorted
-	
-	echo -e "$avg \t\t $med" #prints results
-	rm -f $$tempfile   #deletes temp files
-	rm -f $$tempsorted
-    done < $2
-    echoerr 0
-	
 #calculates column info
-elif [[ $1 == -c* ]];
+elif [[ $1 == -c* ]]
 then
-   echo "calculating column stats";
-    numrows=0
-    while read i  #saves each column to separate temp files and sorts each
-    do
-	numcols=0
-        for num in $i
-        do
-	  echo "$num" >> $$tempfile$numcols
-	  sort -n $$tempfile$numcols -o $$tempfile$numcols
-	  numcols=$(($numcols + 1))
-	done
-	numrows=$(($numrows + 1 ))
-    done < $2
-
-    med=$(($numrows / 2 + 1))
-    count=0
-    while (($count < $numcols))
-    do
-	sum=0
-	tmpcnt=0
-	while read line
+	colRan="false"
+	numrows=0
+	while read i  #saves each column to separate temp files and sorts each
 	do
-	  sum=$(($sum + $line)) #sums all values from column
-	  tmpcnt=$(($tmpcnt + 1))
-	  if [[ $med == $tmpcnt ]]  #finds median value
-	  then
-		medArray[$count]=$line #makes array of medians
-	  fi
-	done < $$tempfile$count	
-	avg=$(($sum / $numrows))
-	rem=$(($sum % $numrows))
-	while (($rem >= ($numrows / 2))) #checks if average needs rounded up
-	do
-	  avg=$(($avg + 1))
-	  rem=0
-	done
-	avgArray[$count]=$avg  #makes array of averages
-	count=$(($count + 1))
-    done
-
+		colRan="true"
+		numcols=0
+		for num in $i
+		do
+			echo "$num" >> $$tmpcol$numcols
+			sort -n $$tmpcol$numcols -o $$tmpcol$numcols
+			numcols=`expr $numcols + 1`
+		done
+		numrows=`expr $numrows + 1`
+	done < $datafilepath
+	
+	if [[ $colRan == "false" ]]	#checks if it actually ran, if it didn't then the file had nothing to read
+	then
+		echoerr "FILE IS EMPTY"
+		exit 1
+	fi
+	
+	med=`expr $numrows / 2`
+	med=`expr $med + 1`		#finds place of median value
+	
 	count=0
+	while [[ $count < $numcols ]]
+	do
+		sum=0
+		tmpcnt=1
+		while read line
+		do
+			sum=`expr $sum + $line` #sums all values from column
+			if [[ $med == $tmpcnt ]]  #finds median value
+			then
+				#add medians to temp file
+				echo -e $line >> $tmpMed
+			fi
+			tmpcnt=`expr $tmpcnt + 1`
+		done < $$tmpcol$count
+		
+		avg=$(( ($sum + ( $numrows / 2)) / $numrows ))	#finds average
+		
+		#adds averages to temp file
+		echo -e $avg >> $tmpAvg
+		count=`expr $count + 1`
+	done
+	
 	echo "Averages:"
-	while (($count < $numcols)) #prints averages
+	while read avg		#prints averages
 	do
-	 echo -e -n "${avgArray[$count]} \t"
-	 count=$(($count + 1))
-	done
+		echo -e -n "$avg\t"
+	done < $tmpAvg
+	
+	echo -e "\nMedians:"
+	while read med		#prints medians
+	do
+		echo -e -n "$med\t"
+	done < $tmpMed
 	echo -e "\n"
-
 	count=0
-	echo "Medians:"
-	while (($count < $numcols)) #prints medians
+	while [[ $count < $numcols ]] #deletes temp column files
 	do
-	 echo -e -n "${medArray[$count]} \t"
-	 count=$(($count + 1))
+		rm -f $$tmpcol$count
+		count=`expr $count + 1`
 	done
-	echo -e "\n"
-
-	count=0
-	while (($count < $numcols)) #deletes temp files
-	do
-	   rm -f $$tempfile$count
-	   count=$(($count + 1))
-	done
-	echoerr 0
+	
+	rm -f $tmpAvg
+	rm -f $tmpMed
+	
+else	#prints error if neither rows nor columns are specified
+	echoerr "./stats {-rows|-cols} [file]"
+	exit 1
 fi
+if [[ -e $$datafile ]]	#removes temp datafile only if it was read from stdin
+then
+	rm -f $$datafile
+fi
+exit 0
